#!/bin/bash
set -euo pipefail

ROOT="$( ( cd "$( dirname "$0" )" && pwd ) )"

CN="$1"

openssl genrsa -out "$ROOT/private/$CN.key.pem" 2048

openssl req \
    -config "$ROOT/openssl.cnf" \
    -subj "/C=DE/ST=Germany/L=Germany/CN=$CN" \
    -key "$ROOT/private/$CN.key.pem" \
    -new -sha256 \
    -out "$ROOT/csr/$CN.csr.pem"

"$ROOT/sign" "$CN"

